name: Build Android APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # خطوة إعادة تسمية ملف الإعدادات
      - name: Prepare Spec File
        run: mv spec.txt buildozer.spec || true

      # تشغيل عملية البناء السحابي
      - name: Build with Buildozer
        uses: ArtemSerebrenninkov/buildozer-action@v1
        with:
          buildozer_version: master
          command: android debug
          
      # رفع ملف الـ APK الناتج لتحميله
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: SofyTube-Final-APK
          path: bin/*.apk
          