name: Build Android APK
on: 
  workflow_dispatch: # يتيح لك تشغيل البناء يدوياً بزر واحد
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # خطوة ذكية لتجهيز ملف الإعدادات مهما كان اسمه
      - name: Prepare Spec File
        run: |
          if [ -f "spec.txt" ]; then mv spec.txt buildozer.spec; fi
          if [ ! -f "buildozer.spec" ]; then echo "Error: spec file missing" && exit 1; fi

      - name: Build with Buildozer
        uses: ArtemSerebrenninkov/buildozer-action@v1
        with:
          buildozer_version: master
          command: android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Sody-App-Final
          path: bin/*.apk
          
