name: Build Android APK
on: 
  workflow_dispatch: # هذا السطر سيظهر لك الزر الأزرق السحري
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare Files
        run: |
          [ -f "spec.txt" ] && mv spec.txt buildozer.spec || echo "Spec already exists"

      - name: Build with Buildozer
        uses: ArtemSerebrenninkov/buildozer-action@v1
        with:
          buildozer_version: master
          command: android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Sody-App-Final
          path: bin/*.apk
          
